language: python
python:
  - 2.7
  - 3.4
  - 3.5
env:
  - DJANGO=django==1.9.0
  - DJANGO=django==1.8.7
install:
  - pip install $DJANGO
  - pip install -e .
script: python src/test_project/manage.py test usertools
notifications:
  email: false
