language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  - DJANGO=django==1.9.0
  - DJANGO=django==1.8.7
matrix:
  exclude:
    - python: 2.6
      env: DJANGO="-e git+https://github.com/django/django@stable/1.7.x#egg=Django"
install:
  - pip install $DJANGO
  - pip install -e .
script: python src/test_project/manage.py test usertools
notifications:
  email: false
